title: Jon Swain
subtitle: Data Scientist and Cheminformatician
email: jonswain123@gmail.com
description: >-
  I am a data scientist and cheminformatician, originally from the UK, but often found in New Zealand. 
  I'm interested in using data science and machine learning to solve problems in drug discovery.
  When not in front of a computer, I can usually be found in the mountains or on the water.
baseurl: ""
url: "https://jonswain.github.io"
show_excerpts: true

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jonswain" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jonathan-swain/"}
    - { platform: twitter, user_url: "https://twitter.com/JonSwain20" }

theme: minima
plugins:
  - jekyll-feed
  - jemoji

google_analytics: G-R6CVGR431E

header_pages:
  - 